CREATE DATABASE IF NOT EXISTS GoAnimals;

USE GoAnimals;

--* SUB TABLES 
CREATE TABLE IF NOT EXISTS BRAND (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    BNAME VARCHAR(255) NOT NULL,  
    OTHER VARCHAR(255),        
    PREMIUM BOOLEAN        
);

CREATE TABLE IF NOT EXISTS KIND (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    KIND VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TYPE_PET (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ANIMAL VARCHAR(255) NOT NULL,
    AGES VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FOR_PET (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GENDER VARCHAR(255) NOT NULL,
    OTHER VARCHAR(255)
);

--* PRODUCTS TABLES

CREATE TABLE IF NOT EXISTS FOOD(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FKIND INT,
    FNAME VARCHAR(255) NOT NULL,
    FBRAND INT,
    FTYPE INT,
    SIZES INT,
    FFOR INT,
    WEIGHTS INT,
    EXTENT VARCHAR(255),
    PICTURE BLOB,

    FOREIGN KEY (FKIND) REFERENCES KIND(ID),
    FOREIGN KEY (FBRAND) REFERENCES BRAND(ID),
    FOREIGN KEY (FTYPE) REFERENCES TYPE_PET(ID),
    FOREIGN KEY (FFOR) REFERENCES FOR_PET(ID)
);

CREATE TABLE IF NOT EXISTS HYGIENE(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    HKIND INT,
    HNAME VARCHAR(255) NOT NULL,
    HBRAND INT,
    HTYPE INT,
    HFOR INT,
    SIZES INT,
    SMELL VARCHAR(255),
    EXTENT VARCHAR(255),
    PICTURE BLOB,

    FOREIGN KEY (HKIND) REFERENCES KIND(ID),
    FOREIGN KEY (HBRAND) REFERENCES BRAND(ID),
    FOREIGN KEY (HTYPE) REFERENCES TYPE_PET(ID),
    FOREIGN KEY (HFOR) REFERENCES FOR_PET(ID)
);

CREATE TABLE IF NOT EXISTS CLOTHES(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CKIND INT,
    CNAME VARCHAR(255) NOT NULL,
    CBRAND INT,
    CTYPE INT,
    CFOR INT,
    EXTENT VARCHAR(255),
    PICTURE BLOB,

    FOREIGN KEY (CKIND) REFERENCES KIND(ID),
    FOREIGN KEY (CBRAND) REFERENCES BRAND(ID),
    FOREIGN KEY (CTYPE) REFERENCES TYPE_PET(ID),
    FOREIGN KEY (CFOR) REFERENCES FOR_PET(ID)
);

-- * MANAGEMENT TABLES

CREATE TABLE IF NOT EXISTS BATCH(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ICA_NUMBER INT,
    BATCH_DATE DATE,
    DUE_DATE DATE,
    PRODUCT INT,
    KIND_OF_PRODUCT VARCHAR(255),
    UNITS INT,
    WORTH DOUBLE,
    MARGIN_OF_GAIN FLOAT
);

CREATE TABLE IF NOT EXISTS INVENTORY(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCT INT,
    KIND_OF_PRODUCT VARCHAR(255),
    BATCH INT,
    TOTAL_UNITS INT,
    PRICE DOUBLE,
    FOREIGN KEY (BATCH) REFERENCES BATCH(ID) ON DELETE CASCADE
);